# Generated by Django 4.2.5 on 2023-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
